In [1]:
import torch
print(torch.__version__)

2.4.1


In [2]:
# Is MPS even available? macOS 12.3+
print(torch.backends.mps.is_available())

# Was the current version of PyTorch built with MPS activated?
print(torch.backends.mps.is_built())

True
True


In [3]:
device = torch.device("mps")

In [10]:
SRB = torch.tensor([
    [1 + 0j, 1 + 0j, 0 + 0j, 0 + 0j, 1 + 0j, 1 + 0j, 0 + 0j, 0 + 0j, 0 + 0j, 0 + 0j, 1 + 0j, 1 + 0j, 1 + 0j, 1 + 0j, 0 + 0j, 0 + 0j, 1.0000000000000 + 0j, 1 + 0j, 1 + 0j, 1.0000000000 + 0j],
    [1 + 0j, 1 + 0j, 0 + 0j, 0 + 0j, 1 + 0j, 1 + 0j, 0 + 0j, 0 + 0j, 0 + 0j, 0 + 0j, -1 + 0j, -1 + 0j, 1 + 0j, 1 + 0j, 0 + 0j, 0 + 0j, 1.0000000000000 + 0j, 1 + 0j, 1 + 0j, 1.0000000000 + 0j],
    [-0.7852733334187016 - 0.2897695287852283j, -0.7852733334187016 + 0.2897695287852283j, 1 + 0j, 1 + 0j, -0.5528870177206528 - 0.2827250057428381j, -0.5528870177206528 + 0.2827250057428381j, 0 + 0j, 0 + 0j, 0 + 0j, 0 + 0j, 0 + 0j, 0 + 0j, 0.1639626598624256 - 0.3397954930374837j, 0.1639626598624256 + 0.3397954930374837j, 1 + 0j, 1 + 0j, 1.0000000000000 + 0j, 0.9417080937432316 - 0.1858714211614355j, 0.9417080937432316 + 0.1858714211614355j, 1.506645862 + 0j],
    [-0.7852733334187016 - 0.2897695287852283j, -0.7852733334187016 + 0.2897695287852283j, -1 + 0j, -1 + 0j, -0.5528870177206528 - 0.2827250057428381j, -0.5528870177206528 + 0.2827250057428381j, 0 + 0j, 0 + 0j, 0 + 0j, 0 + 0j, 0 + 0j, 0 + 0j, 0.1639626598624256 - 0.3397954930374837j, 0.1639626598624256 + 0.3397954930374837j, -1 + 0j, -1 + 0j, 1.0000000000000 + 0j, 0.9417080937432316 - 0.1858714211614355j, 0.9417080937432316 + 0.1858714211614355j, 1.506645862 + 0j],
    [0.871990926958037 + 0.758817005443154j, 0.871990926958037 - 0.758817005443154j, -0.6777923476286921 + 0.1762499689793022j, -0.6777923476286921 - 0.1762499689793022j, -0.2295951307254763 + 0.4428233999018644j, -0.2295951307254763 - 0.4428233999018644j, 0 + 0j, 0 + 0j, 0 + 0j, 0 + 0j, 0 + 0j, 0 + 0j, -1.825783366115600 + 0.2729146776970368j, -1.825783366115600 - 0.2729146776970368j, 1.677792347628693 + 0.4932804239985674j, 1.677792347628693 - 0.4932804239985674j, 1.0000000000000 + 0j, 0.01651345388173584 - 0.1203015223424087j, 0.01651345388173584 + 0.1203015223424087j, 2.1774982320 + 0j],
    [0.871990926958037 + 0.758817005443154j, 0.871990926958037 - 0.758817005443154j, 0.6777923476286921 - 0.1762499689793022j, 0.6777923476286921 + 0.1762499689793022j, -0.2295951307254763 + 0.4428233999018644j, -0.2295951307254763 - 0.4428233999018644j, 0 + 0j, 0 + 0j, 0 + 0j, 0 + 0j, 0 + 0j, 0 + 0j, -1.825783366115600 + 0.2729146776970368j, -1.825783366115600 - 0.2729146776970368j, -1.677792347628693 - 0.4932804239985674j, -1.677792347628693 + 0.4932804239985674j, 1.0000000000000 + 0j, 0.01651345388173584 - 0.1203015223424087j, 0.01651345388173584 + 0.1203015223424087j, 2.1774982320 + 0j],
    [-0.4559430877396571 - 0.6863471542291655j, -0.4559430877396571 + 0.6863471542291655j, 0 + 0j, 0 + 0j, 0.4360373346930196 - 0.1929060282464456j, 0.4360373346930196 + 0.1929060282464456j, 1 + 0j, 0 + 0j, 0 + 0j, 1 + 0j, 0 + 0j, 0 + 0j, -0.4857935745869096 + 0.2066236698318384j, -0.4857935745869096 - 0.2066236698318384j, 0 + 0j, 0 + 0j, 1.0000000000000 + 0j, -0.4529849186518693 - 0.05686355045017387j, -0.4529849186518693 + 0.05686355045017387j, 2.940805993 + 0j],
    [-0.4559430877396571 - 0.6863471542291655j, -0.4559430877396571 + 0.6863471542291655j, 0 + 0j, 0 + 0j, 0.4360373346930196 - 0.1929060282464456j, 0.4360373346930196 + 0.1929060282464456j, -1 + 0j, 0 + 0j, 0 + 0j, -1 + 0j, 0 + 0j, 0 + 0j, -0.4857935745869096 + 0.2066236698318384j, -0.4857935745869096 - 0.2066236698318384j, 0 + 0j, 0 + 0j, 1.0000000000000 + 0j, -0.4529849186518693 - 0.05686355045017387j, -0.4529849186518693 + 0.05686355045017387j, 2.940805993 + 0j],
    [0.316166246945256 + 0.4372668984009098j, 0.316166246945256 - 0.4372668984009098j, 0 + 0j, 0 + 0j, -0.3539360491059364 + 0.1483375774939369j, -0.3539360491059364 - 0.1483375774939369j, 0 + 0j, 1 + 0j, 1 + 0j, 0 + 0j, 0 + 0j, 0 + 0j, 1.760142150147743 - 0.656653486402592j, 1.760142150147743 + 0.656653486402592j, 0 + 0j, 0 + 0j, 1.0000000000000 + 0j, -0.6075410321665820 - 0.0946049188434250j, -0.6075410321665820 + 0.0946049188434250j, 2.457837369 + 0j],
    [0.316166246945256 + 0.4372668984009098j, 0.316166246945256 - 0.4372668984009098j, 0 + 0j, 0 + 0j, -0.3539360491059364 + 0.1483375774939369j, -0.3539360491059364 - 0.1483375774939369j, 0 + 0j, -1 + 0j, -1 + 0j, 0 + 0j, 0 + 0j, 0 + 0j, 1.760142150147743 - 0.656653486402592j, 1.760142150147743 + 0.656653486402592j, 0 + 0j, 0 + 0j, 1.0000000000000 + 0j, -0.6075410321665820 - 0.0946049188434250j, -0.6075410321665820 + 0.0946049188434250j, 2.457837369 + 0j],
    [0.4811463074598212 - 0.458431927744020j, 0.4811463074598212 + 0.458431927744020j, 0 + 0j, 0 + 0j, 0.3786236951053876 - 0.614279498213058j, 0.3786236951053876 + 0.614279498213058j, 0 + 0j, 0 + 0j, 0 + 0j, 0 + 0j, -1j, 1j, -0.1106333003549366 - 0.7049155884797481j, -0.1106333003549366 + 0.7049155884797481j, 0 + 0j, 0 + 0j, -1.0000000000000 + 0j, -0.6009477735051373 - 0.3277934961064556j, -0.6009477735051373 + 0.3277934961064556j, -0.3797111908 + 0j],
    [0.4811463074598212 - 0.458431927744020j, 0.4811463074598212 + 0.458431927744020j, 0 + 0j, 0 + 0j, 0.3786236951053876 - 0.614279498213058j, 0.3786236951053876 + 0.614279498213058j, 0 + 0j, 0 + 0j, 0 + 0j, 0 + 0j, 1j, -1j, -0.1106333003549366 - 0.7049155884797481j, -0.1106333003549366 + 0.7049155884797481j, 0 + 0j, 0 + 0j, -1.0000000000000 + 0j, -0.6009477735051373 - 0.3277934961064556j, -0.6009477735051373 + 0.3277934961064556j, -0.3797111908 + 0j],
    [-0.5106709684035616 + 0.2205728292557225j, -0.5106709684035616 - 0.2205728292557225j, 0.2958583671056089 - 0.535601652501211j, 0.2958583671056089 + 0.535601652501211j, -0.3830083002851859 + 0.2325807734409112j, -0.3830083002851859 - 0.2325807734409112j, 0 + 0j, 0 + 0j, 0 + 0j, 0 + 0j, 0 + 0j, 0 + 0j, -0.2576668701328381 - 0.07798713802515681j, -0.2576668701328381 + 0.07798713802515681j, -0.1291917004389423 - 0.6545721119920909j, -0.1291917004389423 + 0.6545721119920909j, -1.0000000000000 + 0j, -0.6268448251955445 - 0.1969867716546394j, -0.6268448251955445 + 0.1969867716546394j, -0.5720902942 + 0j],
    [-0.5106709684035616 + 0.2205728292557225j, -0.5106709684035616 - 0.2205728292557225j, -0.2958583671056089 + 0.535601652501211j, -0.2958583671056089 - 0.535601652501211j, -0.3830083002851859 + 0.2325807734409112j, -0.3830083002851859 - 0.2325807734409112j, 0 + 0j, 0 + 0j, 0 + 0j, 0 + 0j, 0 + 0j, 0 + 0j, -0.2576668701328381 - 0.07798713802515681j, -0.2576668701328381 + 0.07798713802515681j, 0.1291917004389423 + 0.6545721119920909j, 0.1291917004389423 - 0.6545721119920909j, -1.0000000000000 + 0j, -0.6268448251955445 - 0.1969867716546394j, -0.6268448251955445 + 0.1969867716546394j, -0.5720902942 + 0j],
    [0.767421157254575 - 0.0346464814139747j, 0.767421157254575 + 0.0346464814139747j, -0.10613076256750074 + 0.4151717294672329j, -0.10613076256750074 - 0.4151717294672329j, 0.1850871791152331 + 0.3086990136441816j, 0.1850871791152331 - 0.3086990136441816j, 0 + 0j, 0 + 0j, 0 + 0j, 0 + 0j, 0 + 0j, 0 + 0j, 0.3943742501600817 + 1.256829704452987j, 0.3943742501600817 - 1.256829704452987j, 0.10613076256750074 - 1.161963817241099j, 0.10613076256750074 + 1.161963817241099j, -1.0000000000000 + 0j, -0.0493577799386560 + 0.0668819292202622j, -0.0493577799386560 - 0.0668819292202622j, -0.8268204465 + 0j],
    [0.767421157254575 - 0.0346464814139747j, 0.767421157254575 + 0.0346464814139747j, 0.10613076256750074 - 0.4151717294672329j, 0.10613076256750074 + 0.4151717294672329j, 0.1850871791152331 + 0.3086990136441816j, 0.1850871791152331 - 0.3086990136441816j, 0 + 0j, 0 + 0j, 0 + 0j, 0 + 0j, 0 + 0j, 0 + 0j, 0.3943742501600817 + 1.256829704452987j, 0.3943742501600817 - 1.256829704452987j, -0.10613076256750074 + 1.161963817241099j, -0.10613076256750074 - 1.161963817241099j, -1.0000000000000 + 0j, -0.0493577799386560 + 0.0668819292202622j, -0.0493577799386560 - 0.0668819292202622j, -0.8268204465 + 0j],
    [-0.534018782092664 - 0.1212145302388679j, -0.534018782092664 + 0.1212145302388679j, 0 + 0j, 0 + 0j, 0.04659584863187517 - 0.3408875883801606j, 0.04659584863187517 + 0.3408875883801606j, 0.1250000000000000 - 0.4841229182759271j, 0 + 0j, 0 + 0j, 0.1250000000000000 + 0.4841229182759271j, 0 + 0j, 0 + 0j, 0.1993971922611274 + 0.3195840049846668j, 0.1993971922611274 - 0.3195840049846668j, 0 + 0j, 0 + 0j, -1.0000000000000 + 0j, 0.2535807762921583 + 0.1826575342050237j, 0.2535807762921583 - 0.1826575342050237j, -1.1166569452 + 0j],
    [-0.534018782092664 - 0.1212145302388679j, -0.534018782092664 + 0.1212145302388679j, 0 + 0j, 0 + 0j, 0.04659584863187517 - 0.3408875883801606j, 0.04659584863187517 + 0.3408875883801606j, -0.1250000000000000 + 0.4841229182759271j, 0 + 0j, 0 + 0j, -0.1250000000000000 - 0.4841229182759271j, 0 + 0j, 0 + 0j, 0.1993971922611274 + 0.3195840049846668j, 0.1993971922611274 - 0.3195840049846668j, 0 + 0j, 0 + 0j, -1.0000000000000 + 0j, 0.2535807762921583 + 0.1826575342050237j, 0.2535807762921583 - 0.1826575342050237j, -1.1166569452 + 0j],
    [0.3525793294337168 + 0.0654486514653016j, 0.3525793294337168 - 0.0654486514653016j, 0 + 0j, 0 + 0j, -0.0428878420743755 + 0.2735797803580429j, -0.0428878420743755 - 0.2735797803580429j, 0 + 0j, 0.2500000000000000 - 0.6614378277661476j, 0.2500000000000000 + 0.6614378277661476j, 0 + 0j, 0 + 0j, 0 + 0j, -0.6576156139594402 - 1.168103897189111j, -0.6576156139594402 + 1.168103897189111j, 0 + 0j, 0 + 0j, -1.0000000000000 + 0j, 0.3340895534969667 + 0.2560006143035989j, 0.3340895534969667 - 0.2560006143035989j, -0.9332683538 + 0j],
    [0.3525793294337168 + 0.0654486514653016j, 0.3525793294337168 - 0.0654486514653016j, 0 + 0j, 0 + 0j, -0.0428878420743755 + 0.2735797803580429j, -0.0428878420743755 - 0.2735797803580429j, 0 + 0j, -0.2500000000000000 + 0.6614378277661476j, -0.2500000000000000 - 0.6614378277661476j, 0 + 0j, 0 + 0j, 0 + 0j, -0.6576156139594402 - 1.168103897189111j, -0.6576156139594402 + 1.168103897189111j, 0 + 0j, 0 + 0j, -1.0000000000000 + 0j, 0.3340895534969667 + 0.2560006143035989j, 0.3340895534969667 - 0.2560006143035989j, -0.9332683538 + 0j]
], dtype=torch.cfloat)

In [18]:
def complex_inverse(C):
  A = torch.real(C)
  B = torch.imag(C)
  # construct the left hand side of the system of equations
  # side note: from pytorch 1.7.1 you can use vstack and hstack instead of cat
  lhs = torch.cat([torch.cat([A, -B], dim=1), torch.cat([B, A], dim=1)], dim=0)
  # construct the rhs of the system of equations
  rhs = torch.cat([torch.eye(A.shape[0]).to(A), torch.zeros_like(A)],dim=0)

  # solve the system of equations
  raw, _ = torch.linalg.solve(rhs, lhs)
  # write the solution as a single complex matrix
  iC = raw[:C.shape[0], :] + 1j * raw[C.shape[0]:, :]
  return iC  

In [18]:
# define a 3x3 square matrix of random complex numbers
M = torch.randn(3,3, dtype = torch.complex128)
print("Matrix M:", M)

# compute the inverse of above defined matrix
Minv = torch.linalg.inv(M)
print("Inverse Matrix:", Minv)

print('Product:', M @ Minv)
print()

Matrix M: tensor([[ 0.1070+0.2675j,  0.7854+0.6657j,  1.3760-0.6233j],
        [ 0.0213+0.4168j,  0.1451+0.8693j, -0.3284-0.1949j],
        [ 0.0199+2.0669j,  0.6432-0.4283j,  0.3838-0.0091j]],
       dtype=torch.complex128)
Inverse Matrix: tensor([[ 0.0506+0.1132j,  0.2060-0.2591j, -0.0470-0.4419j],
        [ 0.1810-0.1577j, -0.0079-0.7807j, -0.0074+0.1871j],
        [ 0.4751+0.1990j, -0.5262+0.1912j,  0.0328-0.0448j]],
       dtype=torch.complex128)
Product: tensor([[ 1.0000e+00+5.5511e-17j,  0.0000e+00+1.1102e-16j,
         -1.3878e-17-2.7756e-17j],
        [ 8.3267e-17+6.9389e-17j,  1.0000e+00+2.7756e-17j,
          1.5613e-17-6.9389e-18j],
        [ 0.0000e+00+3.4694e-18j, -8.3267e-17-5.5511e-17j,
          1.0000e+00+0.0000e+00j]], dtype=torch.complex128)



In [14]:
SRB_inverse = torch.linalg.inv(SRB)

In [15]:
print(SRB_inverse)

tensor([[-6.3726e-02-1.1712e-01j, -6.3726e-02-1.1712e-01j,
          1.6106e-02+1.1043e-01j,  1.6106e-02+1.1043e-01j,
          3.3301e-02-1.5048e-01j,  3.3301e-02-1.5048e-01j,
         -5.1326e-02+9.7136e-02j, -5.1326e-02+9.7136e-02j,
          3.1063e-02-6.4893e-02j,  3.1063e-02-6.4893e-02j,
          8.4351e-02+2.7135e-02j,  8.4351e-02+2.7136e-02j,
         -1.7513e-01-1.3725e-01j, -1.7513e-01-1.3725e-01j,
          1.0592e-01+1.7534e-01j,  1.0592e-01+1.7534e-01j,
         -7.9339e-02-2.8106e-01j, -7.9339e-02-2.8106e-01j,
          2.9607e-02+9.0926e-02j,  2.9607e-02+9.0926e-02j],
        [-6.3726e-02+1.1712e-01j, -6.3726e-02+1.1712e-01j,
          1.6106e-02-1.1043e-01j,  1.6106e-02-1.1043e-01j,
          3.3301e-02+1.5048e-01j,  3.3301e-02+1.5048e-01j,
         -5.1326e-02-9.7136e-02j, -5.1326e-02-9.7136e-02j,
          3.1063e-02+6.4893e-02j,  3.1063e-02+6.4893e-02j,
          8.4351e-02-2.7135e-02j,  8.4351e-02-2.7135e-02j,
         -1.7513e-01+1.3725e-01j, -1.7513e-01+1.3725e-0

In [21]:
product = (SRB @ SRB_inverse)

In [29]:
def round_complex(tensor):
    return torch.complex(tensor.real.round(decimals=3), tensor.imag.round(decimals=3))

In [32]:
def display_matrix(matrix):
    print('Matrix')
    for row in matrix:
        print(row)

In [30]:
product = round_complex(product)

In [34]:
display_matrix(product)

Matrix
tensor([1.-0.j, -0.-0.j, 0.+0.j, -0.-0.j, -0.-0.j, -0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.-0.j, -0.+0.j,
        0.+0.j, -0.+0.j, -0.+0.j, -0.+0.j, -0.-0.j, -0.-0.j, 0.-0.j, 0.-0.j])
tensor([-0.-0.j, 1.-0.j, 0.+0.j, -0.-0.j, -0.-0.j, -0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, -0.+0.j,
        0.+0.j, -0.+0.j, -0.+0.j, -0.+0.j, -0.-0.j, -0.-0.j, 0.-0.j, 0.-0.j])
tensor([0.-0.j, -0.+0.j, 1.-0.j, -0.-0.j, 0.+0.j, 0.+0.j, -0.-0.j, -0.-0.j, -0.-0.j, -0.-0.j, -0.-0.j, 0.+0.j,
        -0.-0.j, 0.+0.j, 0.+0.j, 0.-0.j, 0.-0.j, 0.-0.j, 0.+0.j, 0.+0.j])
tensor([0.-0.j, -0.-0.j, -0.-0.j, 1.-0.j, -0.+0.j, 0.+0.j, -0.-0.j, -0.-0.j, 0.+0.j, 0.+0.j, 0.+0.j, -0.+0.j,
        -0.-0.j, -0.-0.j, -0.-0.j, 0.+0.j, -0.+0.j, -0.+0.j, -0.+0.j, -0.+0.j])
tensor([0.-0.j, 0.+0.j, -0.+0.j, 0.-0.j, 1.-0.j, 0.-0.j, -0.+0.j, -0.+0.j, 0.-0.j, 0.-0.j, -0.+0.j, 0.-0.j,
        -0.+0.j, 0.-0.j, 0.-0.j, -0.+0.j, -0.-0.j, -0.-0.j, -0.-0.j, -0.-0.j])
tensor([0.-0.j, 0.+0.j, 0.-0.j, 0.+0.j, 0.-0.j, 1.-0.j, 0